language: cpp

install:
  - sudo apt-get install libgtest-dev

script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

  - cd tagirmi/helloworld
  - cmake .
  - cmake --build .
  - cmake --build . --target test
