language: cpp

install:
  - sudo apt-get install libgtest-dev

before_script:
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
